language: cpp

addons:
  apt:
    packages:
      - llvm-dev

before_script:
  - export CC=clang-5.0
  - export CXX=clang++-5.0

script:
  - mkdir build && cd build
  - cmake ../
  - make -j3
  - make test